model_run_dir = 'X:\Projects\CMP\PBA2050\2050_SFTP_2021'
taz_filepath = 'Y:\champ\landuse\p2021\pba50\2050\2-RunInputsChamp5Parking\tazdata.csv'
out_dir = 'Q:\MTC\Model\ConsistencyReports\2023\Analysis\Data'
forecast_year = 2050