out_dir = 'Q:\MTC\Model\ConsistencyReports\2025\Analysis\CHAMP7-2019-2050'
base_year = 2019
forecast_year = 2050

[champ.base]
# model_run_dir = 'X:\Projects\CHAMP7\Run25z_Market'
taz_filepath = 'Y:\champ\landuse\y2019\dtx_20210207\2-RunInputsChamp5Parking\tazdata.dbf'

[champ.forecast]
model_run_dir = 'X:\Projects\Geary_19th\1a_NoProject_AltLU'  # no standard 2050 baseline for CHAMP 7
# no standard 2050 forecast land use. the one main project using CHAMP 7 (before
# we switched to 7CE) used housing element land use, but the run above used
# preliminary PBA 2050+ as an alternative
taz_filepath = 'Y:\champ\landuse\p2025\pba50p_prelim\2050\2-RunInputsChamp5Parking\tazdata.dbf'

[mtc]
taz_excel_filepath = 'Q:\Model Landuse\PBA2050\20210310\PBA50_FinalBlueprintLandUse_TAZdata.xlsx'
taz_gis_filepath = 'Q:\GIS\Model\TAZ\MTC_TAZ\taz1454.shp'